{
  "code": [
    {
      "prim": "parameter",
      "args": [
        {
          "prim": "or",
          "args": [
            {
              "prim": "unit",
              "annots": [
                "%nop"
              ]
            },
            {
              "prim": "big_map",
              "args": [
                {
                  "prim": "nat"
                },
                {
                  "prim": "string"
                }
              ],
              "annots": [
                "%overwrite"
              ]
            }
          ]
        }
      ]
    },
    {
      "prim": "storage",
      "args": [
        {
          "prim": "big_map",
          "args": [
            {
              "prim": "nat"
            },
            {
              "prim": "string"
            }
          ]
        }
      ]
    },
    {
      "prim": "code",
      "args": [
        [
          {
            "prim": "UNPAIR"
          },
          {
            "prim": "IF_LEFT",
            "args": [
              [
                {
                  "prim": "DROP"
                },
                {
                  "prim": "NIL",
                  "args": [
                    {
                      "prim": "operation"
                    }
                  ]
                },
                {
                  "prim": "PAIR"
                }
              ],
              [
                {
                  "prim": "SWAP"
                },
                {
                  "prim": "DROP"
                },
                {
                  "prim": "NIL",
                  "args": [
                    {
                      "prim": "operation"
                    }
                  ]
                },
                {
                  "prim": "PAIR"
                }
              ]
            ]
          }
        ]
      ]
    }
  ],
  "storage": {
    "int": "4"
  }
}
