{
  "code": [
    {
      "prim": "parameter",
      "args": [
        {
          "prim": "or",
          "args": [
            {
              "prim": "address",
              "annots": [
                "%copy"
              ]
            },
            {
              "prim": "unit",
              "annots": [
                "%nop"
              ]
            }
          ]
        }
      ]
    },
    {
      "prim": "storage",
      "args": [
        {
          "prim": "pair",
          "args": [
            {
              "prim": "nat",
              "annots": [
                "%counter"
              ]
            },
            {
              "prim": "big_map",
              "args": [
                {
                  "prim": "nat"
                },
                {
                  "prim": "string"
                }
              ],
              "annots": [
                "%ledger"
              ]
            }
          ]
        }
      ]
    },
    {
      "prim": "code",
      "args": [
        [
          {
            "prim": "UNPAIR"
          },
          {
            "prim": "IF_LEFT",
            "args": [
              [
                {
                  "prim": "CONTRACT",
                  "args": [
                    {
                      "prim": "big_map",
                      "args": [
                        {
                          "prim": "nat"
                        },
                        {
                          "prim": "string"
                        }
                      ]
                    }
                  ],
                  "annots": [
                    "%overwrite"
                  ]
                },
                {
                  "prim": "IF_NONE",
                  "args": [
                    [
                      {
                        "prim": "PUSH",
                        "args": [
                          {
                            "prim": "string"
                          },
                          {
                            "string": "expected Some"
                          }
                        ]
                      },
                      {
                        "prim": "FAILWITH"
                      }
                    ],
                    []
                  ]
                },
                {
                  "prim": "SWAP"
                },
                {
                  "prim": "DUP"
                },
                {
                  "prim": "DUG",
                  "args": [
                    {
                      "int": "2"
                    }
                  ]
                },
                {
                  "prim": "CDR"
                },
                {
                  "prim": "PUSH",
                  "args": [
                    {
                      "prim": "nat"
                    },
                    {
                      "int": "1"
                    }
                  ]
                },
                {
                  "prim": "DUP",
                  "args": [
                    {
                      "int": "4"
                    }
                  ]
                },
                {
                  "prim": "CAR"
                },
                {
                  "prim": "ADD"
                },
                {
                  "prim": "PAIR"
                },
                {
                  "prim": "NIL",
                  "args": [
                    {
                      "prim": "operation"
                    }
                  ]
                },
                {
                  "prim": "DIG",
                  "args": [
                    {
                      "int": "2"
                    }
                  ]
                },
                {
                  "prim": "PUSH",
                  "args": [
                    {
                      "prim": "mutez"
                    },
                    {
                      "int": "0"
                    }
                  ]
                },
                {
                  "prim": "DIG",
                  "args": [
                    {
                      "int": "4"
                    }
                  ]
                },
                {
                  "prim": "CDR"
                },
                {
                  "prim": "TRANSFER_TOKENS"
                },
                {
                  "prim": "CONS"
                },
                {
                  "prim": "PAIR"
                }
              ],
              [
                {
                  "prim": "DROP"
                },
                {
                  "prim": "NIL",
                  "args": [
                    {
                      "prim": "operation"
                    }
                  ]
                },
                {
                  "prim": "PAIR"
                }
              ]
            ]
          }
        ]
      ]
    }
  ],
  "storage": {
    "prim": "Pair",
    "args": [
      {
        "int": "0"
      },
      {
        "int": "5"
      }
    ]
  }
}
