version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:1.57.0-node
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local/rustup /usr/local/cargo
      - restore_cache:
          keys:
            - storage2sql-v{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
            - storage2sql-v{{ .Environment.CACHE_VERSION }}-
      - run: cargo build
      - save_cache:
          paths:
            - target
            - /usr/local/cargo/registry/index
            - /usr/local/cargo/registry/cache
            - /usr/local/cargo/bin
          key: storage2sql-v{{ .Environment.CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
      - persist_to_workspace:
          root: /
          paths:
            - home/circleci/project
            - usr/local/rustup
            - usr/local/cargo

  tester:
    docker:
      - image: circleci/rust:1.57.0-node
    steps:
      - run: sudo chown -R circleci /usr/local/rustup /usr/local/cargo
      - attach_workspace:
          at: /
      - run: cargo test

  linter:
    docker:
      - image: circleci/rust:1.57.0-node
    steps:
      - run: sudo chown -R circleci /usr/local/rustup /usr/local/cargo
      - attach_workspace:
          at: /
      - run: rustup component add clippy
      - run: cargo clippy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tester:
          requires:
            - build
      - linter:
          requires:
            - build
